pipeline:
  - name: Clean old environment
    type: command
    command: rm -rf vendor/ && rm composer.lock || true
    directory: $APP_ROOT

  - name: Re-install platform
    type: command
    command: composer install
    directory: $APP_ROOT

  - name: Drush site-install
    type: command
    command: drush -y site-install
    directory: $HTTP_ROOT

  - name: Enable all modules
    type: command
    command: drush -y en hdbt hdbt_admin helfi_tpr helfi_tunnistamo
    directory: $HTTP_ROOT

  - name: Set default theme
    type: command
    command: drush -y config-set system.theme default hdbt
    directory: $HTTP_ROOT

  - name: Set default admin theme
    type: command
    command: drush -y config-set system.theme admin hdbt_admin
    directory: $HTTP_ROOT

  - name: Create new test user
    type: command
    command: drush user:create $DRUPAL_USER_NAME --password $DRUPAL_USER_PASS --mail $DRUPAL_USER_MAIL
    directory: $HTTP_ROOT

  - name: Drush clear cache
    type: command
    command: drush -y cr
    directory: $HTTP_ROOT
