pipeline:
  - name: Clean old environment
    type: command
    command: rm -rf vendor/
    directory: $APP_ROOT

  - name: Re-install platform
    type: command
    command: composer install
    directory: $APP_ROOT

  - name: Drush site-install
    type: command
    command: drush -y site-install
    directory: $HTTP_ROOT

  - name: Drush clear cache
    type: command
    command: drush -y cr
    directory: $HTTP_ROOT
