on: [push]
name: CI
env:
  SIMPLETEST_DB: "mysql://drupal:drupal@db:3306/drupal"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  COMPOSER_MEMORY_LIMIT: -1
  GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/city-of-helsinki/drupal-php-docker:7.4

    services:
      db:
        image: druidfi/db:mysql5.7-drupal
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set variables
        run: echo "DRUPAL_ROOT=$HOME/drupal" >> $GITHUB_ENV

      - name: Build composer project
        run: composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main $DRUPAL_ROOT --no-interaction --repository https://repository.drupal.hel.ninja/

      - name: Install Drupal
        run: |
          cd $DRUPAL_ROOT
          php -d sendmail_path=$(which true); drush --yes -v site-install --db-url="$SIMPLETEST_DB"
          drush en helfi_platform_config

      - name: Make sure Drupal is installed properly
        run: |
          cd $DRUPAL_ROOT
          drush runserver $SIMPLETEST_BASE_URL &
          sleep 5
          # Make sure Drupal is installed
          curl -s -o /dev/null -I -w "%{http_code}" $SIMPLETEST_BASE_URL
          curl -s -o /dev/null -I -w "%{http_code}" $SIMPLETEST_BASE_URL | grep -q 200
