on: [push]
name: CI
env:
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  COMPOSER_MEMORY_LIMIT: -1
  GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: druidfi/db:mysql5.7-drupal
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, mysql, dom, gd, xml, curl, openssl

      - name: Override simpletest url
        run: echo "SIMPLETEST_DB=mysql://drupal:drupal@127.0.0.1:${{ job.services.db.ports[3306] }}/drupal" >> $GITHUB_ENV

      - name: Build project
        run: |
          composer install

      - name: Install Drupal
        run: |
          php -d sendmail_path=$(which true); vendor/bin/drush --yes -v site-install --db-url="$SIMPLETEST_DB"
          vendor/bin/drush en helfi_platform_config

      - name: Make sure Drupal is installed properly
        run: |
          vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
          sleep 5
          # Make sure Drupal is installed
          curl -s -o /dev/null -I -w "%{http_code}" $SIMPLETEST_BASE_URL/user/login | grep -q 200

      - uses: actions/checkout@v2
        with:
          name: City-of-Helsinki/helfi-test-automation
          path: helfi-test-automation

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Build with Maven
        run: |
          cd helfi-test-automation/
          ls -la
          mvn -Drobot.tag=CRITICAL -Drobot.browser=chromeheadless -Pplatform -B clean install
